# Generated by Django 5.2.8 on 2025-11-23 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('house', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('cell', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'collector'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('collector', 'Collector'), ('resident', 'Resident')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('assigned_collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stwms.collector')),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stwms.location')),
            ],
        ),
        migrations.CreateModel(
            name='WasteBin',
            fields=[
                ('WasteBin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fill_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('full', 'Full'), ('intermediate', 'Intermediate'), ('empty', 'Empty')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stwms.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_bins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('defective', 'Defective'), ('working', 'Working'), ('check up', 'Check up')], max_length=10)),
                ('last_reading', models.DateTimeField(auto_now=True)),
                ('waste_bin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='stwms.wastebin')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('assigned_collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stwms.collector')),
                ('bins', models.ManyToManyField(related_name='routes', to='stwms.wastebin')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('bin_full', 'Bin Full'), ('sensor_error', 'Sensor Error'), ('overheat', 'Overheat'), ('leakage', 'Leakage')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stwms.wastebin')),
            ],
        ),
    ]
