# Generated by Django 5.2.8 on 2025-11-29 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stwms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='collector',
            name='user',
            field=models.OneToOneField(limit_choices_to={'profile__role': 'collector'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('collector', 'Collector'), ('resident', 'Resident')], default='resident', max_length=20),
        ),
        migrations.AlterField(
            model_name='wastebin',
            name='status',
            field=models.CharField(choices=[('full', 'Full'), ('intermediate', 'Intermediate'), ('empty', 'Empty'), ('maintenance', 'Maintenance')], max_length=50),
        ),
    ]
