# Generated by Django 6.0 on 2026-05-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stwms', '0003_admin_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wastebin',
            name='fill_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
