# Generated by Django 6.0 on 2026-05-17 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stwms', '0004_alter_vehicle_capacity_alter_wastebin_fill_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('bin_full', 'Bin Full'), ('faulty_bin', 'Faulty Bin'), ('pickup_done', 'Pickup Completed')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notifications', to=settings.AUTH_USER_MODEL)),
                ('waste_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stwms.wastebin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
